// Demo woningen — worden getoond wanneer de database nog leeg is
// of wanneer Supabase nog niet geconfigureerd is.
// Verwijder deze data niet — ze dienen als visuele demo voor bezoekers.

export const DEMO_WONINGEN = [
  {
    id: "demo-1",
    status: "actief",
    type: "appartement",
    stad: "Tivat",
    regio: "Tivat Riviera",
    adres: "Porto Montenegro, Tivat",
    lat: 42.4344,
    lng: 18.6966,
    vraagprijs: 185000,
    oppervlakte_m2: 68,
    perceel_m2: null,
    kamers: 3,
    slaapkamers: 2,
    badkamers: 1,
    bouwjaar: 2022,
    tuin: false,
    zwembad: true,
    garage: true,
    zeezicht: true,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Modern appartement op loopafstand van Porto Montenegro jachthaven. Volledig afgewerkt, gemeenschappelijk zwembad, beveiligde parkeerplaats. Ideaal als vakantiewoning of verhuurinvestering — hoge bezettingsgraad dankzij de nabijheid van de luchthaven.",
    omschrijving_en: "Modern apartment within walking distance of Porto Montenegro marina. Fully finished, communal pool, secured parking. Ideal as holiday home or rental investment.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://images.unsplash.com/photo-1682936770708-3a8d9301a151?fm=jpg&q=75&w=900&auto=format&fit=crop",
    fotos: ["https://images.unsplash.com/photo-1682936770708-3a8d9301a151?fm=jpg&q=75&w=900&auto=format&fit=crop"],
    professionele_fotos: true,
    demo: true,
  },
  {
    id: "demo-2",
    status: "actief",
    type: "villa",
    stad: "Kotor",
    regio: "Boka Kotorska",
    adres: "Prčanj, Kotor",
    lat: 42.4572,
    lng: 18.7219,
    vraagprijs: 420000,
    oppervlakte_m2: 195,
    perceel_m2: 650,
    kamers: 6,
    slaapkamers: 4,
    badkamers: 3,
    bouwjaar: 2019,
    tuin: true,
    zwembad: true,
    garage: true,
    zeezicht: true,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Luxe villa met panoramisch uitzicht over de Boka Kotorska baai. Privé zwembad, grote tuin met olijfbomen, drie verdiepingen. Op 10 minuten rijden van de oude stad van Kotor (UNESCO). Volledig gemeubileerd, inclusief domotica-systeem.",
    omschrijving_en: "Luxury villa with panoramic views over Boka Kotorska bay. Private pool, large garden with olive trees, three floors. 10 minutes drive from Kotor old town (UNESCO).",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://images.unsplash.com/photo-1614122027743-50a9e6e8002f?fm=jpg&q=75&w=900&auto=format&fit=crop",
    fotos: ["https://images.unsplash.com/photo-1614122027743-50a9e6e8002f?fm=jpg&q=75&w=900&auto=format&fit=crop"],
    professionele_fotos: true,
    demo: true,
  },
  {
    id: "demo-3",
    status: "actief",
    type: "appartement",
    stad: "Bar",
    regio: "Bar Riviera",
    adres: "Šušanj, Bar",
    lat: 42.1078,
    lng: 19.1007,
    vraagprijs: 98000,
    oppervlakte_m2: 54,
    perceel_m2: null,
    kamers: 2,
    slaapkamers: 1,
    badkamers: 1,
    bouwjaar: 2021,
    tuin: false,
    zwembad: false,
    garage: false,
    zeezicht: true,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Compact appartement met zeezicht in de rustige wijk Šušanj, op 200 meter van het strand. Nieuwe afwerking, energiezuinig gebouw. Bar groeit snel als haven- en toeristenstad — goed investeringspotentieel tegen lage instapprijs.",
    omschrijving_en: "Compact apartment with sea views in the quiet Šušanj neighbourhood, 200 metres from the beach. New finish, energy-efficient building.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://images.unsplash.com/photo-1719772355253-cac25a978d76?fm=jpg&q=75&w=900&auto=format&fit=crop",
    fotos: ["https://images.unsplash.com/photo-1719772355253-cac25a978d76?fm=jpg&q=75&w=900&auto=format&fit=crop"],
    professionele_fotos: false,
    demo: true,
  },
  {
    id: "demo-4",
    status: "actief",
    type: "grond",
    stad: "Dobre Vode",
    regio: "Bar",
    adres: "Dobre Vode",
    lat: 42.1433,
    lng: 19.0872,
    vraagprijs: 55000,
    oppervlakte_m2: null,
    perceel_m2: 1200,
    kamers: null,
    slaapkamers: null,
    badkamers: null,
    bouwjaar: null,
    tuin: false,
    zwembad: false,
    garage: false,
    zeezicht: true,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Bouwgrond van 1.200 m² met panoramisch zeezicht in het rustige dorp Dobre Vode, ten noorden van Bar. Legale grond met bouwvergunning voor villa tot 300 m². Alle nutsvoorzieningen aanwezig. Ideaal voor zelfbouw of projectontwikkeling.",
    omschrijving_en: "Building plot of 1,200 m² with panoramic sea views in the quiet village of Dobre Vode, north of Bar. Legal land with building permit for villa up to 300 m².",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://images.unsplash.com/photo-1668301157539-ede800d169d4?fm=jpg&q=75&w=900&auto=format&fit=crop",
    fotos: ["https://images.unsplash.com/photo-1668301157539-ede800d169d4?fm=jpg&q=75&w=900&auto=format&fit=crop"],
    professionele_fotos: false,
    demo: true,
  },
  {
    id: "demo-5",
    status: "actief",
    type: "huis",
    stad: "Kolašin",
    regio: "Kolašin",
    adres: "Centar, Kolašin",
    lat: 42.8233,
    lng: 19.5219,
    vraagprijs: 145000,
    oppervlakte_m2: 130,
    perceel_m2: 420,
    kamers: 5,
    slaapkamers: 3,
    badkamers: 2,
    bouwjaar: 2015,
    tuin: true,
    zwembad: false,
    garage: true,
    zeezicht: false,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Ruim gezinshuis in het hart van Kolašin, het wintersportcentrum van Montenegro. Op 5 minuten lopen van de ski-liften en het Biogradska Gora nationaal park. Grote tuin, garage, volledig ingericht. Groeiende markt voor wintersport- en eco-toerisme.",
    omschrijving_en: "Spacious family home in the heart of Kolašin, Montenegro's winter sports centre. 5 minutes walk from ski lifts and Biogradska Gora national park.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://images.unsplash.com/photo-1634902252038-532bdbb280a6?fm=jpg&q=75&w=900&auto=format&fit=crop",
    fotos: ["https://images.unsplash.com/photo-1634902252038-532bdbb280a6?fm=jpg&q=75&w=900&auto=format&fit=crop"],
    professionele_fotos: false,
    demo: true,
  },
  {
    id: "demo-6",
    status: "actief",
    type: "project",
    stad: "Bijelo Polje",
    regio: "Bijelo Polje",
    adres: "Centar, Bijelo Polje",
    lat: 43.0344,
    lng: 19.7481,
    vraagprijs: 72000,
    oppervlakte_m2: 62,
    perceel_m2: null,
    kamers: 3,
    slaapkamers: 2,
    badkamers: 1,
    bouwjaar: 2024,
    tuin: false,
    zwembad: false,
    garage: true,
    zeezicht: false,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Off-plan nieuwbouwproject in het stadscentrum van Bijelo Polje — de grootste stad in Noord-Montenegro. Oplevering Q2 2025. Moderne afwerking, lift, ondergrondse parkeergarage. Bijelo Polje is de geboortestreek van de oprichtersfamilie van Obrov Real Estate en profiteert van groeiende regionale investeringen.",
    omschrijving_en: "Off-plan new-build project in the city centre of Bijelo Polje — the largest city in northern Montenegro. Completion Q2 2025. Modern finish, lift, underground parking.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://images.unsplash.com/photo-1615352916571-99807ec84e29?fm=jpg&q=75&w=900&auto=format&fit=crop",
    fotos: ["https://images.unsplash.com/photo-1615352916571-99807ec84e29?fm=jpg&q=75&w=900&auto=format&fit=crop"],
    professionele_fotos: false,
    demo: true,
  },
];

// GPS-coördinaten per stad voor de straal-zoekfunctie
export const STAD_COORDS = {
  "tivat":        { lat: 42.4344, lng: 18.6966 },
  "kotor":        { lat: 42.4247, lng: 18.7712 },
  "budva":        { lat: 42.2869, lng: 18.8400 },
  "bar":          { lat: 42.1078, lng: 19.1007 },
  "ulcinj":       { lat: 41.9250, lng: 19.2119 },
  "dobre vode":   { lat: 42.1433, lng: 19.0872 },
  "kolašin":      { lat: 42.8233, lng: 19.5219 },
  "kolašin":      { lat: 42.8233, lng: 19.5219 },
  "bijelo polje": { lat: 43.0344, lng: 19.7481 },
  "podgorica":    { lat: 42.4415, lng: 19.2636 },
  "herceg novi":  { lat: 42.4533, lng: 18.5375 },
  "cetinje":      { lat: 42.3931, lng: 18.9214 },
  "nikšić":       { lat: 42.7731, lng: 18.9444 },
  "berane":       { lat: 42.8437, lng: 19.8733 },
};

// Afstand berekenen in km tussen twee GPS-punten (Haversine formule)
export function afstandKm(lat1, lng1, lat2, lng2) {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLng = (lng2 - lng1) * Math.PI / 180;
  const a = Math.sin(dLat/2) ** 2 + Math.cos(lat1 * Math.PI/180) * Math.cos(lat2 * Math.PI/180) * Math.sin(dLng/2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
}
