// Demo woningen — worden getoond wanneer de database nog leeg is.
export const DEMO_WONINGEN = [
  {
    id: "demo-1",
    status: "actief",
    type: "appartement",
    stad: "Tivat",
    regio: "Tivat Riviera",
    adres: "Porto Montenegro, Tivat",
    lat: 42.4344,
    lng: 18.6966,
    vraagprijs: 185000,
    oppervlakte_m2: 68,
    perceel_m2: null,
    kamers: 3,
    slaapkamers: 2,
    badkamers: 1,
    bouwjaar: 2022,
    tuin: false,
    zwembad: true,
    garage: true,
    zeezicht: true,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Modern appartement op loopafstand van Porto Montenegro jachthaven. Volledig afgewerkt, gemeenschappelijk zwembad, beveiligde parkeerplaats. Ideaal als vakantiewoning of verhuurinvestering.",
    omschrijving_en: "Modern apartment within walking distance of Porto Montenegro marina. Fully finished, communal pool, secured parking.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Porto_Montenegro.jpg/1280px-Porto_Montenegro.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Porto_Montenegro.jpg/1280px-Porto_Montenegro.jpg"],
    professionele_fotos: false,
    demo: true,
  },
  {
    id: "demo-2",
    status: "actief",
    type: "villa",
    stad: "Kotor",
    regio: "Boka Kotorska",
    adres: "Prčanj, Kotor",
    lat: 42.4572,
    lng: 18.7219,
    vraagprijs: 420000,
    oppervlakte_m2: 195,
    perceel_m2: 650,
    kamers: 6,
    slaapkamers: 4,
    badkamers: 3,
    bouwjaar: 2019,
    tuin: true,
    zwembad: true,
    garage: true,
    zeezicht: true,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Luxe villa met panoramisch uitzicht over de Boka Kotorska baai. Privé zwembad, grote tuin met olijfbomen, drie verdiepingen. Op 10 minuten rijden van de oude stad van Kotor (UNESCO).",
    omschrijving_en: "Luxury villa with panoramic views over Boka Kotorska bay. Private pool, large garden, three floors. 10 minutes from Kotor old town (UNESCO).",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Kotor_bay_from_fortress.jpg/1280px-Kotor_bay_from_fortress.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Kotor_bay_from_fortress.jpg/1280px-Kotor_bay_from_fortress.jpg"],
    professionele_fotos: false,
    demo: true,
  },
  {
    id: "demo-3",
    status: "actief",
    type: "appartement",
    stad: "Bar",
    regio: "Bar Riviera",
    adres: "Šušanj, Bar",
    lat: 42.1078,
    lng: 19.1007,
    vraagprijs: 98000,
    oppervlakte_m2: 54,
    perceel_m2: null,
    kamers: 2,
    slaapkamers: 1,
    badkamers: 1,
    bouwjaar: 2021,
    tuin: false,
    zwembad: false,
    garage: false,
    zeezicht: true,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Compact appartement met zeezicht in de rustige wijk Šušanj, op 200 meter van het strand. Nieuwe afwerking, energiezuinig gebouw.",
    omschrijving_en: "Compact apartment with sea views in the quiet Šušanj neighbourhood, 200 metres from the beach.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Bar_Montenegro.jpg/1280px-Bar_Montenegro.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Bar_Montenegro.jpg/1280px-Bar_Montenegro.jpg"],
    professionele_fotos: false,
    demo: true,
  },
  {
    id: "demo-4",
    status: "actief",
    type: "grond",
    stad: "Dobre Vode",
    regio: "Bar",
    adres: "Dobre Vode",
    lat: 42.1433,
    lng: 19.0872,
    vraagprijs: 55000,
    oppervlakte_m2: null,
    perceel_m2: 1200,
    kamers: null,
    slaapkamers: null,
    badkamers: null,
    bouwjaar: null,
    tuin: false,
    zwembad: false,
    garage: false,
    zeezicht: true,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Bouwgrond van 1.200 m² met panoramisch zeezicht in Dobre Vode, ten noorden van Bar. Legale grond met bouwvergunning voor villa tot 300 m². Alle nutsvoorzieningen aanwezig.",
    omschrijving_en: "Building plot of 1,200 m² with panoramic sea views in Dobre Vode, north of Bar. Legal land with building permit for villa up to 300 m².",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Montenegro_coast.jpg/1280px-Montenegro_coast.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Montenegro_coast.jpg/1280px-Montenegro_coast.jpg"],
    professionele_fotos: false,
    demo: true,
  },
  {
    id: "demo-5",
    status: "actief",
    type: "huis",
    stad: "Kolašin",
    regio: "Kolašin",
    adres: "Centar, Kolašin",
    lat: 42.8233,
    lng: 19.5219,
    vraagprijs: 145000,
    oppervlakte_m2: 130,
    perceel_m2: 420,
    kamers: 5,
    slaapkamers: 3,
    badkamers: 2,
    bouwjaar: 2015,
    tuin: true,
    zwembad: false,
    garage: true,
    zeezicht: false,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Ruim gezinshuis in het hart van Kolašin, het wintersportcentrum van Montenegro. Op 5 minuten lopen van de skiliften en het Biogradska Gora nationaal park. Grote tuin, garage, volledig ingericht.",
    omschrijving_en: "Spacious family home in the heart of Kolašin, Montenegro's winter sports centre. 5 minutes walk from ski lifts and Biogradska Gora national park.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Biogradska_gora.jpg/1280px-Biogradska_gora.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Biogradska_gora.jpg/1280px-Biogradska_gora.jpg"],
    professionele_fotos: false,
    demo: true,
  },
  {
    id: "demo-6",
    status: "actief",
    type: "project",
    stad: "Bijelo Polje",
    regio: "Bijelo Polje",
    adres: "Centar, Bijelo Polje",
    lat: 43.0344,
    lng: 19.7481,
    vraagprijs: 72000,
    oppervlakte_m2: 62,
    perceel_m2: null,
    kamers: 3,
    slaapkamers: 2,
    badkamers: 1,
    bouwjaar: 2024,
    tuin: false,
    zwembad: false,
    garage: true,
    zeezicht: false,
    legale_grond: true,
    papieren_orde: true,
    geasfalteerde_weg: true,
    water: true,
    elektriciteit: true,
    omschrijving_nl: "Off-plan nieuwbouwproject in het stadscentrum van Bijelo Polje, de grootste stad in Noord-Montenegro. Oplevering Q2 2025. Moderne afwerking, lift, ondergrondse parkeergarage.",
    omschrijving_en: "Off-plan new-build project in the city centre of Bijelo Polje, the largest city in northern Montenegro. Completion Q2 2025.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Bijelo_Polje_grad.jpg/1280px-Bijelo_Polje_grad.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Bijelo_Polje_grad.jpg/1280px-Bijelo_Polje_grad.jpg"],
    professionele_fotos: false,
    demo: true,
  },
  {
    id: "demo-7",
    status: "actief",
    type: "appartement",
    stad: "Mostar",
    regio: "Bosna i Hercegovina",
    adres: "Stari Grad, Mostar",
    lat: 43.3438,
    lng: 17.8078,
    vraagprijs: 89000,
    oppervlakte_m2: 58,
    perceel_m2: null,
    kamers: 3,
    slaapkamers: 2,
    badkamers: 1,
    bouwjaar: 2020,
    tuin: false, zwembad: false, garage: false, zeezicht: false,
    legale_grond: true, papieren_orde: true, geasfalteerde_weg: true, water: true, elektriciteit: true,
    omschrijving_nl: "Modern appartement nabij de iconische Stari Most brug in Mostar. Volledig gerenoveerd, instapklaar. Mostar is een van de snelst groeiende toeristische bestemmingen in de Balkan.",
    omschrijving_en: "Modern apartment near the iconic Stari Most bridge in Mostar. Fully renovated, move-in ready.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Mostar_Old_Bridge.jpg/1280px-Mostar_Old_Bridge.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Mostar_Old_Bridge.jpg/1280px-Mostar_Old_Bridge.jpg"],
    professionele_fotos: false, demo: true,
  },
  {
    id: "demo-8",
    status: "actief",
    type: "huis",
    stad: "Split",
    regio: "Dalmacija",
    adres: "Meje, Split",
    lat: 43.5089,
    lng: 16.4289,
    vraagprijs: 310000,
    oppervlakte_m2: 140,
    perceel_m2: 280,
    kamers: 5,
    slaapkamers: 3,
    badkamers: 2,
    bouwjaar: 2017,
    tuin: true, zwembad: false, garage: true, zeezicht: true,
    legale_grond: true, papieren_orde: true, geasfalteerde_weg: true, water: true, elektriciteit: true,
    omschrijving_nl: "Ruim huis met zeezicht in de populaire wijk Meje, op 10 minuten van het historische centrum van Split. Directe vluchten vanuit Amsterdam, sterke verhuurmarkt.",
    omschrijving_en: "Spacious house with sea views in the popular Meje neighbourhood, 10 minutes from Split's historic centre.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Split_Croatia.jpg/1280px-Split_Croatia.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Split_Croatia.jpg/1280px-Split_Croatia.jpg"],
    professionele_fotos: false, demo: true,
  },
  {
    id: "demo-9",
    status: "actief",
    type: "appartement",
    stad: "Pula",
    regio: "Istra",
    adres: "Centar, Pula",
    lat: 44.8683,
    lng: 13.8481,
    vraagprijs: 195000,
    oppervlakte_m2: 72,
    perceel_m2: null,
    kamers: 3,
    slaapkamers: 2,
    badkamers: 1,
    bouwjaar: 2019,
    tuin: false, zwembad: false, garage: true, zeezicht: false,
    legale_grond: true, papieren_orde: true, geasfalteerde_weg: true, water: true, elektriciteit: true,
    omschrijving_nl: "Modern appartement in het hart van Pula, nabij de beroemde Romeinse arena. Pula is de hoofdstad van Istrië en een populaire bestemming voor Europese investeerders.",
    omschrijving_en: "Modern apartment in the heart of Pula, near the famous Roman arena. Pula is the capital of Istria.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Pula_Arena_at_sunset.jpg/1280px-Pula_Arena_at_sunset.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Pula_Arena_at_sunset.jpg/1280px-Pula_Arena_at_sunset.jpg"],
    professionele_fotos: false, demo: true,
  },
  {
    id: "demo-10",
    status: "actief",
    type: "grond",
    stad: "Strunjan",
    regio: "Primorska, Slovenija",
    adres: "Strunjan",
    lat: 45.5275,
    lng: 13.6144,
    vraagprijs: 145000,
    oppervlakte_m2: null,
    perceel_m2: 800,
    kamers: null,
    slaapkamers: null,
    badkamers: null,
    bouwjaar: null,
    tuin: false, zwembad: false, garage: false, zeezicht: true,
    legale_grond: true, papieren_orde: true, geasfalteerde_weg: true, water: true, elektriciteit: true,
    omschrijving_nl: "Bouwkavel van 800 m² met panoramisch uitzicht op de Adriatische Zee in het Strunjan Landschapspark in Slovenië. Zeldzame kans in een beschermd kustgebied dicht bij Portorož.",
    omschrijving_en: "Building plot of 800 m² with panoramic Adriatic views in Strunjan Landscape Park, Slovenia. Rare opportunity near Portorož.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Strunjan_coast.jpg/1280px-Strunjan_coast.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Strunjan_coast.jpg/1280px-Strunjan_coast.jpg"],
    professionele_fotos: false, demo: true,
  },
  {
    id: "demo-11",
    status: "actief",
    type: "appartement",
    stad: "Tuzla",
    regio: "Bosna i Hercegovina",
    adres: "Centar, Tuzla",
    lat: 44.5384,
    lng: 18.6737,
    vraagprijs: 65000,
    oppervlakte_m2: 55,
    perceel_m2: null,
    kamers: 2,
    slaapkamers: 1,
    badkamers: 1,
    bouwjaar: 2018,
    tuin: false, zwembad: false, garage: false, zeezicht: false,
    legale_grond: true, papieren_orde: true, geasfalteerde_weg: true, water: true, elektriciteit: true,
    omschrijving_nl: "Instapklaar appartement in het centrum van Tuzla, een van de grootste steden van Bosnië. Lage instapprijs, groeiende economische regio nabij de EU-grens.",
    omschrijving_en: "Move-in ready apartment in the centre of Tuzla, one of Bosnia's largest cities. Low entry price, growing economic region near the EU border.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Tuzla_panorama.jpg/1280px-Tuzla_panorama.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Tuzla_panorama.jpg/1280px-Tuzla_panorama.jpg"],
    professionele_fotos: false, demo: true,
  },
  {
    id: "demo-12",
    status: "actief",
    type: "huis",
    stad: "Sarajevo",
    regio: "Bosna i Hercegovina",
    adres: "Ilidža, Sarajevo",
    lat: 43.8308,
    lng: 18.3103,
    vraagprijs: 178000,
    oppervlakte_m2: 165,
    perceel_m2: 350,
    kamers: 6,
    slaapkamers: 4,
    badkamers: 2,
    bouwjaar: 2014,
    tuin: true, zwembad: false, garage: true, zeezicht: false,
    legale_grond: true, papieren_orde: true, geasfalteerde_weg: true, water: true, elektriciteit: true,
    omschrijving_nl: "Ruim gezinshuis in de groene wijk Ilidža, op 20 minuten van het centrum van Sarajevo. Grote tuin, garage, nabij thermaal bad en recreatiegebied.",
    omschrijving_en: "Spacious family home in the green Ilidža district, 20 minutes from Sarajevo city centre. Large garden, garage, near thermal baths.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Sarajevo_Old_Town.jpg/1280px-Sarajevo_Old_Town.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Sarajevo_Old_Town.jpg/1280px-Sarajevo_Old_Town.jpg"],
    professionele_fotos: false, demo: true,
  },
  {
    id: "demo-13",
    status: "actief",
    type: "villa",
    stad: "Ulcinj",
    regio: "Ulcinj Riviera",
    adres: "Velika Plaža, Ulcinj",
    lat: 41.8950,
    lng: 19.2403,
    vraagprijs: 265000,
    oppervlakte_m2: 175,
    perceel_m2: 500,
    kamers: 6,
    slaapkamers: 4,
    badkamers: 3,
    bouwjaar: 2018,
    tuin: true, zwembad: true, garage: true, zeezicht: true,
    legale_grond: true, papieren_orde: true, geasfalteerde_weg: true, water: true, elektriciteit: true,
    omschrijving_nl: "Luxe villa op 300 meter van Velika Plaža, het langste zandstrand van de Adriatische Zee. Privé zwembad, grote tuin, volledig gemeubileerd. Ulcinj grenst aan Albanië en heeft het warmste klimaat van Montenegro.",
    omschrijving_en: "Luxury villa 300 metres from Velika Plaža, the longest sandy beach on the Adriatic. Private pool, large garden, fully furnished.",
    verkoper_naam: "Obrov Real Estate",
    verkoper_email: "info@obrovrealestate.nl",
    verkoper_telefoon: "+31612345678",
    verkoper_is_makelaar: true,
    makelaar_bedrijf: "Obrov Real Estate",
    hoofdfoto: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Ulcinj_beach.jpg/1280px-Ulcinj_beach.jpg",
    fotos: ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Ulcinj_beach.jpg/1280px-Ulcinj_beach.jpg"],
    professionele_fotos: false, demo: true,
  },
];

export const STAD_COORDS = {
  "tivat":        { lat: 42.4344, lng: 18.6966 },
  "kotor":        { lat: 42.4247, lng: 18.7712 },
  "budva":        { lat: 42.2869, lng: 18.8400 },
  "bar":          { lat: 42.1078, lng: 19.1007 },
  "ulcinj":       { lat: 41.9250, lng: 19.2119 },
  "dobre vode":   { lat: 42.1433, lng: 19.0872 },
  "kolašin":      { lat: 42.8233, lng: 19.5219 },
  "bijelo polje": { lat: 43.0344, lng: 19.7481 },
  "podgorica":    { lat: 42.4415, lng: 19.2636 },
  "herceg novi":  { lat: 42.4533, lng: 18.5375 },
  "cetinje":      { lat: 42.3931, lng: 18.9214 },
  "nikšić":       { lat: 42.7731, lng: 18.9444 },
  "berane":       { lat: 42.8437, lng: 19.8733 },
  "split":        { lat: 43.5081, lng: 16.4402 },
  "dubrovnik":    { lat: 42.6507, lng: 18.0944 },
  "makarska":     { lat: 43.2964, lng: 17.0181 },
  "zadar":        { lat: 44.1194, lng: 15.2314 },
  "mostar":       { lat: 43.3438, lng: 17.8078 },
  "sarajevo":     { lat: 43.8563, lng: 18.4131 },
  "neum":         { lat: 42.9231, lng: 17.6153 },
  "ljubljana":    { lat: 46.0569, lng: 14.5058 },
  "portorož":     { lat: 45.5133, lng: 13.5925 },
  "bled":         { lat: 46.3683, lng: 14.1146 },
  "mostar":       { lat: 43.3438, lng: 17.8078 },
  "split":        { lat: 43.5081, lng: 16.4402 },
  "pula":         { lat: 44.8683, lng: 13.8481 },
  "strunjan":     { lat: 45.5275, lng: 13.6144 },
  "tuzla":        { lat: 44.5384, lng: 18.6737 },
  "sarajevo":     { lat: 43.8563, lng: 18.4131 },
  "ulcinj":       { lat: 41.9250, lng: 19.2119 },
};

export function afstandKm(lat1, lng1, lat2, lng2) {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLng = (lng2 - lng1) * Math.PI / 180;
  const a = Math.sin(dLat/2) ** 2 + Math.cos(lat1 * Math.PI/180) * Math.cos(lat2 * Math.PI/180) * Math.sin(dLng/2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
}
